# Configuration file for the Sphinx documentation builder.
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import sys
from pathlib import Path

sys.path.insert(0, Path("../../src").resolve().as_posix())
sys.path.append(Path("extensions").resolve().as_posix())

# -- Project information -----------------------------------------------------

project = "freqfit"
copyright = "2024, the UW LEGEND Group on Behalf of the LEGEND Collaboration"
author = "UW LEGEND Group"

# Use importlib.metadata instead of deprecated pkg_resources
try:
    from importlib.metadata import version, PackageNotFoundError

    release = version("freqfit")
    version = ".".join(release.split(".")[:2])
except PackageNotFoundError:
    release = "unknown"
    version = "unknown"

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinx_copybutton",
    "sphinx_inline_tabs",
    "nbsphinx",
    "myst_parser",
    "IPython.sphinxext.ipython_console_highlighting",
    "numbadoc",
]

# File types Sphinx will parse
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

master_doc = "index"

# MyST parser settings (for .md files)
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
]

# -- HTML output -------------------------------------------------------------

# Furo theme
html_theme = "furo"
html_theme_options = {
    "source_repository": "https://github.com/cenpa/freqfit",
    "source_branch": "main",
    "source_directory": "docs/source",
    "navigation_with_keys": True,
}
html_title = f"{project} {release}"

# Uncomment and update path if a logo exists:
# html_logo = "_static/logo.png"

html_static_path = ["_static"]

# -- Napoleon (NumPy-style docstrings) ---------------------------------------

napoleon_numpy_docstring = True
napoleon_google_docstring = False
napoleon_use_ivar = True
napoleon_use_rtype = False
napoleon_custom_sections = ["JSON Configuration Example"]

# -- Intersphinx -------------------------------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "numba": ("https://numba.readthedocs.io/en/stable", None),
    "scipy": ("https://docs.scipy.org/doc/scipy", None),
    "pandas": ("https://pandas.pydata.org/docs", None),
    "matplotlib": ("https://matplotlib.org/stable", None),
    "h5py": ("https://docs.h5py.org/en/stable", None),
    "pint": ("https://pint.readthedocs.io/en/stable", None),
}

# -- Autodoc -----------------------------------------------------------------

autodoc_default_options = {
    "members": True,
    "undoc-members": False,
    "show-inheritance": True,
    "ignore-module-all": True,
}

# Include __init__() docstring in class docstring
autoclass_content = "both"
autodoc_typehints = "description"
autodoc_typehints_description_target = "documented_params"
autodoc_typehints_format = "short"

# -- Autosummary -------------------------------------------------------------

autosummary_generate = True

# -- nbsphinx ----------------------------------------------------------------

nbsphinx_execute = "never"  # Don't re-execute notebooks on build

nbsphinx_epilog = f"""
----

This page has been automatically generated by nbsphinx_ and can be run as a
Jupyter_ notebook available in the `freqfit repository
<https://github.com/cenpa/freqfit/tree/main/docs/source/notebooks>`_.

.. _nbsphinx: https://nbsphinx.readthedocs.io/
.. _Jupyter: https://jupyter.org/
"""

# -- Warnings ----------------------------------------------------------------

suppress_warnings = [
    "ref.python",
]
